### ISSUE TITLE
System.InvalidOperationException : msg_seqno too low

### ISSUE THREAD

**Issue by knocte** [nblockchain/TgSharp#25]
https://github.com/nblockchain/TgSharp/runs/1133633770

```
1) Error : TgSharp.Tests.TgSharpTestsNUnit.SendMessageTest
System.InvalidOperationException : msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)
   at TgSharp.Core.Network.MtProtoSender.HandleBadMsgNotification(UInt64 messageId, Int32 sequence, BinaryReader messageReader) in D:\a\TgSharp\TgSharp\src\TgSharp.Core\Network\MtProtoSender.cs:line 402
   at TgSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request, CancellationToken token) in D:\a\TgSharp\TgSharp\src\TgSharp.Core\Network\MtProtoSender.cs:line 209
   at TgSharp.Core.Network.MtProtoSender.<Receive>d__8.MoveNext() in D:\a\TgSharp\TgSharp\src\TgSharp.Core\Network\MtProtoSender.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TgSharp.Core.TelegramClient.<ConnectInternalAsync>d__14.MoveNext() in D:\a\TgSharp\TgSharp\src\TgSharp.Core\TelegramClient.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TgSharp.Core.TelegramClient.<ConnectAsync>d__13.MoveNext() in D:\a\TgSharp\TgSharp\src\TgSharp.Core\TelegramClient.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by knocte** [comment]
Afshin please never close an issue without explaining why.

In this case, this issue was just hit when I was implementing launching tests in CI: https://github.com/nblockchain/TgSharp/pull/26
